1. Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:

In [4]:
import numpy as np

np.set_printoptions(precision=2, suppress=True)

In [22]:
a = np.array([[-1, 2], [-6, 6]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  2]
 [-6  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.55 -0.45]
 [-0.83 -0.89]]


3. Установите, считается ли вектор  𝑥=(1,1)  собственным вектором этого линейного оператора.

In [23]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]


Вектор 𝑥=(1,1) не является собственным вектором этого линейного оператора

2. Дан оператор поворота на 180 градусов, задаваемый матрицей.

In [2]:
def rotateMatrix(mat):
 
    if not mat or not len(mat):
        return
 
    N = len(mat)
 
    for i in range(N // 2):
        for j in range(N):
            temp = mat[i][j]
            mat[i][j] = mat[N - i - 1][N - j - 1]
            mat[N - i - 1][N - j - 1] = temp
 
    if N % 2 == 1:
        for j in range(N // 2):
            temp = mat[N // 2][j]
            mat[N // 2][j] = mat[N // 2][N - j - 1]
            mat[N // 2][N - j - 1] = temp
 
 
if __name__ == '__main__':
 
    mat = [
        [-1, 0],
        [0, -1],
    ]
 
    rotateMatrix(mat)
 
    for r in mat:
        print(r)

[-1, 0]
[0, -1]


Покажите, что любой вектор считается для него собственным.

In [16]:
r = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(r)
 
print(f'Матрица A:\n{r}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1  0]
 [ 0 -1]]
Собственные векторы:
[[1. 0.]
 [0. 1.]]


4. Пусть линейный оператор задан матрицей

In [5]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]
